#!/usr/bin/env bash
# 源站防护：
# 1) Nginx real_ip：仅信任 Cloudflare 回源网段
# 2) UFW：80/443 仅允许 Cloudflare（SSH 不动）
#
#   bash cloudflare-origin-protect.sh
#   bash cloudflare-origin-protect.sh --undo-ufw
set -euo pipefail

UNDO_UFW=0
[[ "${1:-}" == "--undo-ufw" ]] && UNDO_UFW=1

CF_V4_URL="https://www.cloudflare.com/ips-v4"
CF_V6_URL="https://www.cloudflare.com/ips-v6"
REALIP_CONF=/etc/nginx/conf.d/cloudflare-realip.conf
TAG="cf-origin-welfare"

echo "==> Fetch Cloudflare IP ranges"
mapfile -t CF_V4 < <(curl -fsSL "$CF_V4_URL" | tr -d '\r' | grep -E '^[0-9]')
mapfile -t CF_V6 < <(curl -fsSL "$CF_V6_URL" | tr -d '\r' | grep -E '^[0-9a-fA-F:]' || true)
if [[ ${#CF_V4[@]} -lt 5 ]]; then
  echo "failed to fetch CF IPv4 list" >&2
  exit 1
fi
echo "IPv4=${#CF_V4[@]} IPv6=${#CF_V6[@]}"

echo "==> Nginx real_ip -> ${REALIP_CONF}"
{
  echo "# generated by cloudflare-origin-protect.sh $(date -u +%Y-%m-%dT%H:%MZ)"
  for cidr in "${CF_V4[@]}"; do
    echo "set_real_ip_from ${cidr};"
  done
  for cidr in "${CF_V6[@]}"; do
    echo "set_real_ip_from ${cidr};"
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "${REALIP_CONF}"

SITE=/etc/nginx/sites-available/welfare
if [[ -f "${SITE}" ]]; then
  cp -a "${SITE}" "${SITE}.bak-cf-$(date +%Y%m%d%H%M%S)"
  # Ensure X-Real-IP is post-real_ip $remote_addr
  if grep -q 'proxy_set_header X-Real-IP' "${SITE}"; then
    sed -i 's|proxy_set_header X-Real-IP .*|proxy_set_header X-Real-IP $remote_addr;|' "${SITE}"
  else
    sed -i '/proxy_set_header Host/a\        proxy_set_header X-Real-IP $remote_addr;' "${SITE}"
  fi
  if ! grep -q 'proxy_set_header CF-Connecting-IP' "${SITE}"; then
    sed -i '/proxy_set_header X-Real-IP/a\        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;' "${SITE}"
  fi
fi

nginx -t
systemctl reload nginx
echo "Nginx OK"

ufw_delete_by_comment() {
  local comment="$1"
  # repeatedly delete first matching numbered rule
  local guard=0
  while [[ $guard -lt 200 ]]; do
    guard=$((guard + 1))
    local line num
    line=$(ufw status numbered 2>/dev/null | grep "${comment}" | head -1 || true)
    [[ -z "$line" ]] && break
    num=$(echo "$line" | sed -n 's/^\[\s*\([0-9]\+\)\].*/\1/p')
    [[ -z "$num" ]] && break
    yes | ufw delete "$num" >/dev/null || break
  done
}

if [[ "${UNDO_UFW}" -eq 1 ]]; then
  echo "==> Undo UFW CF rules"
  ufw_delete_by_comment "${TAG}"
  ufw allow 'Nginx Full' 2>/dev/null || {
    ufw allow 80/tcp
    ufw allow 443/tcp
  }
  ufw status | head -30
  exit 0
fi

if ! command -v ufw >/dev/null; then
  echo "ufw missing; only Nginx real_ip applied"
  exit 0
fi

echo "==> UFW Cloudflare-only 80/443"
# Remove previous tagged rules and broad web allows
ufw_delete_by_comment "${TAG}"
yes | ufw delete allow 'Nginx Full' 2>/dev/null || true
yes | ufw delete allow 'Nginx Full (v6)' 2>/dev/null || true
yes | ufw delete allow 80/tcp 2>/dev/null || true
yes | ufw delete allow 443/tcp 2>/dev/null || true
yes | ufw delete allow 80,443/tcp 2>/dev/null || true

for cidr in "${CF_V4[@]}"; do
  ufw allow from "${cidr}" to any port 80,443 proto tcp comment "${TAG}"
done
for cidr in "${CF_V6[@]}"; do
  ufw allow from "${cidr}" to any port 80,443 proto tcp comment "${TAG}"
done

# Default deny for everyone else on web ports (evaluated after specific allows)
ufw deny 80/tcp comment "${TAG}-deny"
ufw deny 443/tcp comment "${TAG}-deny"

# SSH must stay
ufw status | grep -q OpenSSH || ufw allow OpenSSH || ufw allow 22/tcp

ufw --force enable
ufw reload

echo "=== ufw (first 40 lines) ==="
ufw status numbered | head -40
echo
echo "Done. Verify:"
echo "  curl -sS https://youth.huishengbook.us.ci/api/health"
echo "  # from non-CF IP, direct https://ORIGIN_IP should be blocked/timeout"
