"""baseline

对齐当前 ORM 模型定义的基线迁移，覆盖以下 11 张表：
accounts / merchants / user_profiles / user_verifications /
coupon_templates / coupon_instances / redemption_logs / audit_logs /
point_accounts / point_ledgers / email_codes。

部署说明：
- 新机器空库：直接 `alembic upgrade head` 即可建表。
- 已有库（曾用 create_all + ensure_schema）：执行 `alembic stamp head`
  把当前 schema 标记为已应用 baseline，不实际执行 DDL，后续新增迁移正常增量应用。
- baseline 的 downgrade 会删表，仅在全新部署的清理场景使用，生产数据请勿 downgrade。

Revision ID: 2c984c17c453
Revises:
Create Date: 2026-07-31 21:09:54.223454

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c984c17c453'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.Enum('register', 'reset_password', 'bind_email', name='emailcodepurpose', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_codes_email'), 'email_codes', ['email'], unique=False)
    op.create_index(op.f('ix_email_codes_purpose'), 'email_codes', ['purpose'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'issue_admin', 'merchant', 'user', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_role'), 'accounts', ['role'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('coupon_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('cost_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_templates_merchant_id'), 'coupon_templates', ['merchant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('coupon_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('unused', 'used', 'void', 'expired', name='couponstatus', native_enum=False, length=32), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_by', sa.String(length=36), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_coupon_code')
    )
    op.create_index(op.f('ix_coupon_instances_code'), 'coupon_instances', ['code'], unique=False)
    op.create_index(op.f('ix_coupon_instances_merchant_id'), 'coupon_instances', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_coupon_instances_status'), 'coupon_instances', ['status'], unique=False)
    op.create_index(op.f('ix_coupon_instances_template_id'), 'coupon_instances', ['template_id'], unique=False)
    op.create_index(op.f('ix_coupon_instances_user_id'), 'coupon_instances', ['user_id'], unique=False)
    op.create_table('point_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('point_ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_ledgers_user_id'), 'point_ledgers', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('student_no', sa.String(length=64), nullable=False),
    sa.Column('organization', sa.String(length=128), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('bank_card_encrypted', sa.Text(), nullable=True),
    sa.Column('bank_card_last4', sa.String(length=4), nullable=False),
    sa.Column('bank_card_bank_name', sa.String(length=64), nullable=False),
    sa.Column('bank_card_bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='verifystatus', native_enum=False, length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_user_profiles_verify_status'), 'user_profiles', ['verify_status'], unique=False)
    op.create_table('redemption_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon_instances.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_logs_coupon_id'), 'redemption_logs', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_redemption_logs_merchant_id'), 'redemption_logs', ['merchant_id'], unique=False)
    op.create_table('user_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('material_note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='verifystatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_verifications_profile_id'), 'user_verifications', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verifications_profile_id'), table_name='user_verifications')
    op.drop_table('user_verifications')
    op.drop_index(op.f('ix_redemption_logs_merchant_id'), table_name='redemption_logs')
    op.drop_index(op.f('ix_redemption_logs_coupon_id'), table_name='redemption_logs')
    op.drop_table('redemption_logs')
    op.drop_index(op.f('ix_user_profiles_verify_status'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_point_ledgers_user_id'), table_name='point_ledgers')
    op.drop_table('point_ledgers')
    op.drop_table('point_accounts')
    op.drop_index(op.f('ix_coupon_instances_user_id'), table_name='coupon_instances')
    op.drop_index(op.f('ix_coupon_instances_template_id'), table_name='coupon_instances')
    op.drop_index(op.f('ix_coupon_instances_status'), table_name='coupon_instances')
    op.drop_index(op.f('ix_coupon_instances_merchant_id'), table_name='coupon_instances')
    op.drop_index(op.f('ix_coupon_instances_code'), table_name='coupon_instances')
    op.drop_table('coupon_instances')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_coupon_templates_merchant_id'), table_name='coupon_templates')
    op.drop_table('coupon_templates')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_role'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_email_codes_purpose'), table_name='email_codes')
    op.drop_index(op.f('ix_email_codes_email'), table_name='email_codes')
    op.drop_table('email_codes')
    # ### end Alembic commands ###
